services:
  db:
    image: postgres:16-alpine
    container_name: rg-media-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rg_media
    volumes:
      - rg_media_pg:/var/lib/postgresql/data

volumes:
  rg_media_pg:
